"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Sparkles, Copy, Download, Youtube, FileText, Loader2, AlertCircle } from "lucide-react";
import { motion } from "framer-motion";

export default function Home() {
  const [youtubeUrl, setYoutubeUrl] = useState("");
  const [style, setStyle] = useState("informative");
  const [audience, setAudience] = useState("beginner");
  const [length, setLength] = useState("medium");
  const [loading, setLoading] = useState(false);
  const [blog, setBlog] = useState<any | null>(null);
  const [error, setError] = useState("");

  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError("");
    setBlog(null);

    try {
      const res = await fetch("/api/generate-blog", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ youtubeUrl, style, audience, length }),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "Something went wrong");
      }

      // Redirect to the new blog page
      router.push(`/blog/${data.blogId}`);

    } catch (err: any) {
      setError(err.message);
      setLoading(false); // Only stop loading on error, otherwise keep loading during redirect
    }
  };

  const copyToClipboard = () => {
    if (!blog) return;
    const text = `${blog.title}\n\n${blog.subtitle}\n\n${blog.sections.map((s: any) => `### ${s.heading}\n${s.content}`).join("\n\n")}\n\n### Conclusion\n${blog.conclusion}`;
    navigator.clipboard.writeText(text);
    alert("Blog copied to clipboard!");
  };

  const downloadMarkdown = () => {
    if (!blog) return;
    const text = `# ${blog.title}\n\n> ${blog.subtitle}\n\n${blog.sections.map((s: any) => `## ${s.heading}\n${s.content}`).join("\n\n")}\n\n## Conclusion\n${blog.conclusion}\n\n---\nGenerated by Tube2Blog`;
    const blob = new Blob([text], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${blog.title.replace(/\s+/g, "_").toLowerCase()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950 text-slate-100 flex flex-col items-center px-4 py-10">
      <div className="max-w-4xl w-full">
        {/* Header */}
        <header className="mb-12 text-center">
          <div className="inline-flex items-center justify-center p-2 bg-indigo-500/10 rounded-full mb-4 border border-indigo-500/20">
            <Sparkles className="w-4 h-4 text-indigo-400 mr-2" />
            <span className="text-xs font-medium text-indigo-300">AgentAI Buildathon 2024</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold mb-4 bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 to-cyan-400">
            Tube2Blog
          </h1>
          <p className="text-slate-400 text-lg max-w-xl mx-auto">
            Turn any YouTube video into a polished, SEO-ready blog post in seconds using AI.
          </p>
        </header>

        {/* Input Form */}
        <motion.form
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          onSubmit={handleSubmit}
          className="glass-panel rounded-2xl p-6 md:p-8 mb-10 shadow-2xl"
        >
          <div className="mb-6">
            <label className="block text-sm font-medium mb-2 text-slate-300">
              YouTube Video URL
            </label>
            <div className="relative">
              <Youtube className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-500" />
              <input
                type="url"
                required
                placeholder="https://www.youtube.com/watch?v=..."
                value={youtubeUrl}
                onChange={(e) => setYoutubeUrl(e.target.value)}
                className="w-full rounded-xl bg-slate-950/50 border border-slate-700 pl-10 pr-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-all placeholder:text-slate-600"
              />
            </div>
          </div>

          <div className="grid md:grid-cols-3 gap-4 mb-8">
            <div>
              <label className="block text-sm font-medium mb-2 text-slate-300">Style</label>
              <select
                value={style}
                onChange={(e) => setStyle(e.target.value)}
                className="w-full rounded-xl bg-slate-950/50 border border-slate-700 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-all"
                suppressHydrationWarning
              >
                <option value="informative">Informative</option>
                <option value="storytelling">Storytelling</option>
                <option value="listicle">Listicle</option>
                <option value="technical">Technical Deep Dive</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium mb-2 text-slate-300">Audience</label>
              <select
                value={audience}
                onChange={(e) => setAudience(e.target.value)}
                className="w-full rounded-xl bg-slate-950/50 border border-slate-700 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-all"
                suppressHydrationWarning
              >
                <option value="beginner">Beginner</option>
                <option value="intermediate">Intermediate</option>
                <option value="advanced">Advanced</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium mb-2 text-slate-300">Length</label>
              <select
                value={length}
                onChange={(e) => setLength(e.target.value)}
                className="w-full rounded-xl bg-slate-950/50 border border-slate-700 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-all"
                suppressHydrationWarning
              >
                <option value="short">Short</option>
                <option value="medium">Medium</option>
                <option value="long">Long</option>
              </select>
            </div>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full inline-flex items-center justify-center rounded-xl bg-indigo-600 hover:bg-indigo-500 px-6 py-3.5 text-sm font-semibold text-white shadow-lg shadow-indigo-500/20 transition-all hover:-translate-y-0.5 disabled:opacity-50 disabled:hover:translate-y-0 disabled:cursor-not-allowed"
            suppressHydrationWarning
          >
            {loading ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Generating Blog...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4 mr-2" />
                Generate Blog
              </>
            )}
          </button>

          {error && (
            <div className="mt-4 p-4 bg-red-500/10 border border-red-500/20 rounded-xl flex items-start text-red-400 text-sm">
              <AlertCircle className="w-5 h-5 mr-2 flex-shrink-0" />
              <p>{error}</p>
            </div>
          )}
        </motion.form>

        {/* Loading Skeleton */}
        {loading && (
          <div className="space-y-6 animate-pulse">
            <div className="h-8 bg-slate-800/50 rounded-lg w-3/4 mx-auto" />
            <div className="space-y-3">
              <div className="h-4 bg-slate-800/50 rounded w-full" />
              <div className="h-4 bg-slate-800/50 rounded w-full" />
              <div className="h-4 bg-slate-800/50 rounded w-5/6" />
            </div>
          </div>
        )}

        {/* Blog Result */}
        {blog && (
          <motion.article
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="glass-panel rounded-2xl p-8 md:p-10 shadow-2xl relative overflow-hidden"
          >
            <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500" />

            <div className="flex justify-between items-start mb-8 gap-4">
              <div>
                <h2 className="text-3xl md:text-4xl font-bold mb-3 text-white leading-tight">
                  {blog.title}
                </h2>
                <p className="text-lg text-indigo-300 font-medium">{blog.subtitle}</p>
              </div>
              <div className="flex gap-2 shrink-0">
                <button
                  onClick={copyToClipboard}
                  className="p-2 hover:bg-slate-800 rounded-lg transition-colors text-slate-400 hover:text-white"
                  title="Copy to Clipboard"
                >
                  <Copy className="w-5 h-5" />
                </button>
                <button
                  onClick={downloadMarkdown}
                  className="p-2 hover:bg-slate-800 rounded-lg transition-colors text-slate-400 hover:text-white"
                  title="Download Markdown"
                >
                  <Download className="w-5 h-5" />
                </button>
              </div>
            </div>

            <div className="space-y-8">
              {blog.sections?.map((section: any, idx: number) => (
                <section key={idx} className="prose prose-invert max-w-none">
                  {section.heading && (
                    <h3 className="text-xl font-bold text-white mb-3 flex items-center">
                      <span className="w-1.5 h-6 bg-indigo-500 rounded-full mr-3" />
                      {section.heading}
                    </h3>
                  )}
                  <div className="text-slate-300 leading-relaxed whitespace-pre-line pl-4 border-l border-slate-800">
                    {section.content}
                  </div>
                </section>
              ))}

              {blog.conclusion && (
                <section className="mt-8 pt-8 border-t border-slate-800">
                  <h3 className="text-xl font-bold text-white mb-3">Conclusion</h3>
                  <p className="text-slate-300 leading-relaxed whitespace-pre-line">
                    {blog.conclusion}
                  </p>
                </section>
              )}
            </div>

            {blog.tags && (
              <div className="mt-8 flex flex-wrap gap-2">
                {blog.tags.map((tag: string, idx: number) => (
                  <span
                    key={idx}
                    className="px-3 py-1 bg-slate-800/50 border border-slate-700 rounded-full text-xs font-medium text-slate-400"
                  >
                    #{tag}
                  </span>
                ))}
              </div>
            )}
          </motion.article>
        )}
      </div>
    </main>
  );
}
