"use client";

import { Share2, Copy, Download, Check, Twitter, Linkedin, MessageCircle } from "lucide-react";
import { useState, useEffect } from "react";
import toast from "react-hot-toast";
import { FaTwitter, FaLinkedin, FaWhatsapp } from "react-icons/fa";

export default function ClientBlogActions({ blog }: { blog: any }) {
    const [copied, setCopied] = useState(false);

    const [shareUrl, setShareUrl] = useState("");

    // Use useEffect to get the actual window location on the client
    useEffect(() => {
        if (typeof window !== 'undefined') {
            setShareUrl(`${window.location.origin}/blog/${blog.id}`);
        }
    }, [blog.id]);

    const shareText = `${blog.title} - ${blog.subtitle}`;

    const copyToClipboard = () => {
        navigator.clipboard.writeText(shareUrl);
        setCopied(true);
        toast.success("Link copied to clipboard!");
        setTimeout(() => setCopied(false), 2000);
    };

    const downloadMarkdown = () => {
        const text = `# ${blog.title}\n\n> ${blog.subtitle}\n\n${blog.sections.map((s: any) => `## ${s.heading}\n${s.content}`).join("\n\n")}\n\n## Conclusion\n${blog.conclusion}\n\n---\nGenerated by Tube2Blog`;
        const blob = new Blob([text], { type: "text/markdown" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${blog.title.replace(/\s+/g, "_").toLowerCase()}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        toast.success("Markdown downloaded!");
    };

    const shareToTwitter = () => {
        const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`;
        window.open(url, "_blank");
    };

    const shareToLinkedIn = () => {
        const url = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`;
        window.open(url, "_blank");
    };

    const shareToWhatsApp = () => {
        const url = `https://wa.me/?text=${encodeURIComponent(`${shareText} ${shareUrl}`)}`;
        window.open(url, "_blank");
    };

    return (
        <div className="flex gap-2 items-center">
            <button
                onClick={shareToTwitter}
                className="p-2 text-slate-500 hover:text-blue-400 hover:bg-blue-50 rounded-lg transition-colors"
                title="Share on Twitter"
            >
                <FaTwitter className="w-5 h-5" />
            </button>
            <button
                onClick={shareToLinkedIn}
                className="p-2 text-slate-500 hover:text-blue-700 hover:bg-blue-50 rounded-lg transition-colors"
                title="Share on LinkedIn"
            >
                <FaLinkedin className="w-5 h-5" />
            </button>
            <button
                onClick={shareToWhatsApp}
                className="p-2 text-slate-500 hover:text-green-500 hover:bg-green-50 rounded-lg transition-colors"
                title="Share on WhatsApp"
            >
                <FaWhatsapp className="w-5 h-5" />
            </button>

            <div className="w-px h-6 bg-slate-200 mx-1" />

            <button
                onClick={copyToClipboard}
                className="p-2 text-slate-500 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors"
                title="Copy Link"
            >
                {copied ? <Check className="w-5 h-5 text-green-500" /> : <Copy className="w-5 h-5" />}
            </button>
            <button
                onClick={downloadMarkdown}
                className="p-2 text-slate-500 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors"
                title="Download Markdown"
            >
                <Download className="w-5 h-5" />
            </button>
        </div>
    );
}
