"use client";

import { Share2, Copy, Download, Check } from "lucide-react";
import { useState } from "react";
import toast from "react-hot-toast";

export default function ClientBlogActions({ blog }: { blog: any }) {
    const [copied, setCopied] = useState(false);

    const copyToClipboard = () => {
        const text = `${blog.title}\n\n${blog.subtitle}\n\n${blog.sections.map((s: any) => `### ${s.heading}\n${s.content}`).join("\n\n")}\n\n### Conclusion\n${blog.conclusion}`;
        navigator.clipboard.writeText(text);
        setCopied(true);
        toast.success("Content copied to clipboard!");
        setTimeout(() => setCopied(false), 2000);
    };

    const shareLink = () => {
        navigator.clipboard.writeText(window.location.href);
        toast.success("Link copied to clipboard!");
    };

    const downloadMarkdown = () => {
        const text = `# ${blog.title}\n\n> ${blog.subtitle}\n\n${blog.sections.map((s: any) => `## ${s.heading}\n${s.content}`).join("\n\n")}\n\n## Conclusion\n${blog.conclusion}\n\n---\nGenerated by Tube2Blog`;
        const blob = new Blob([text], { type: "text/markdown" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${blog.title.replace(/\s+/g, "_").toLowerCase()}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        toast.success("Markdown downloaded!");
    };

    return (
        <div className="flex gap-2">
            <button
                onClick={shareLink}
                className="p-2 text-slate-500 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors"
                title="Share Link"
            >
                <Share2 className="w-5 h-5" />
            </button>
            <button
                onClick={copyToClipboard}
                className="p-2 text-slate-500 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors"
                title="Copy Content"
            >
                {copied ? <Check className="w-5 h-5 text-green-500" /> : <Copy className="w-5 h-5" />}
            </button>
            <button
                onClick={downloadMarkdown}
                className="p-2 text-slate-500 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors"
                title="Download Markdown"
            >
                <Download className="w-5 h-5" />
            </button>
        </div>
    );
}
